apps/blog/urls.py
from django.urls import path

from .views import BlogList, BlogPage

app_name = 'apps.blog'
urlpatterns = [
    path('', BlogList.as_view(), name='blog_list'),
    path('<slug:slug>/', BlogPage.as_view(), name="blog_page"),
]

voxsnap/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from rest_framework import routers
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token

from apps.leads.views import (PackagesView, QuestionaireView,
                              TimDraperPlaylistView, MailingListView)
# from apps.analytics.views import PlaysStatsListView
from apps.narrations.views import \
    NarrationDetailsView as APINarrationDetailsView
from apps.narrations.views import \
    NarrationsListView as APINarrationsListView
from apps.narrations.views import \
    NarratorsListView as APINarratorsListView
from apps.narrations.views import \
    PlaylistViewSet as APIPlaylistViewSet
from apps.narrations.views import \
    UrlWordCountView as APIUrlWordCountView
from apps.player.views import (AudioHubView, ItemLibraryView, LibraryPageView,
                               PlaylistLibraryView, SubcategoryView)
from apps.player.views import player as player_js_view
from apps.sales.views import (AdditionalServicesListView, BillingListView,
                              CreateOrderView, ValidatePromoCode, AtriumPayment)
from apps.users.views import (CurrentUserView, NotificationsViewSet,
                              UserDetailsView)
import apps.dashboard.django_dash

router = routers.DefaultRouter()
router.register(r'notifications', NotificationsViewSet)
router.register(r'playlists', APIPlaylistViewSet)

api_urlpatterns = (
    [
        path('me/', CurrentUserView.as_view(), name='current_user'),
        path('narrator/', APINarratorsListView.as_view(), name='narrators'),
        path('narrations/', APINarrationsListView.as_view(),
             name='narrations'),
        path('narrations/<int:pk>',
             APINarrationDetailsView.as_view(),
             name='narration_details'),
        path('word-count/', APIUrlWordCountView.as_view(), name='word_count'),
        path('order-prev/',
             CreateOrderView.as_view(),
             name='narrations_order-prev'),
        path('order/', CreateOrderView.as_view(), name='narrations_order'),
        path('validate-promo-code/',
             ValidatePromoCode.as_view(),
             name='validate_promo_code'),
        path('user-details/', UserDetailsView.as_view(), name='user_details'),
        path('billing/', BillingListView.as_view(), name='billing'),
        path('additional-services/',
             AdditionalServicesListView.as_view(),
             name='services'),
        path('subcategory/', SubcategoryView.as_view(), name='subcategories'),
        # path('analytics/plays/', PlaysStatsListView.as_view(),
        # name='analytics'),
        path('rest-auth/', include('rest_auth.urls')),
        path(r'api-token-auth/', obtain_jwt_token),
        path(r'api-token-verify/', verify_jwt_token),

        path('mailinglist/', MailingListView.as_view()),

        path('', include(router.urls)),
    ],
    'api')

dashboard_patterns = (
    [
        # path(r'', TemplateView.as_view(template_name='react_index.html'),
        # name='home'),
        path(r'order-prev/',
             TemplateView.as_view(template_name='react_index.html'),
             name='order_narrationsprev'),
        path(r'order/',
             TemplateView.as_view(template_name='react_index.html'),
             name='order_narrations'),
        path(r'payment/',
             TemplateView.as_view(template_name='react_index.html'),
             name='payment'),
        path(r'thankyou/',
             TemplateView.as_view(template_name='react_index.html'),
             name='order_complete'),
        path(r'narrations/',
             TemplateView.as_view(template_name='react_index.html'),
             name='narrations_list'),
        path(r'narrations/<int:id>',
             TemplateView.as_view(template_name='react_index.html'),
             name='narration_details'),
        path(r'playlists/',
             TemplateView.as_view(template_name='react_index.html'),
             name='playlists_list'),
        path(r'playlists/<int:id>',
             TemplateView.as_view(template_name='react_index.html'),
             name='playlist_details'),
        path(r'playlists/new',
             TemplateView.as_view(template_name='react_index.html'),
             name='new_playlist'),
        path(r'distribution/',
             TemplateView.as_view(template_name='react_index.html'),
             name='distribution'),
        path(r'analytics/', TemplateView.as_view(
        template_name='react_index.html'), name='analytics'),
        path(r'settings/',
             TemplateView.as_view(template_name='react_index.html'),
             name='settings'),
        path(r'billing/',
             TemplateView.as_view(template_name='react_index.html'),
             name='billing'),
        path(r'notifications/',
             TemplateView.as_view(template_name='react_index.html'),
             name='notifications'),
        path(r'password-change/',
             TemplateView.as_view(template_name='react_index.html'),
             name='password-change'),
        path(r'player-customization/',
             TemplateView.as_view(template_name='player_customization.html'),
             name='player-customization'),
    ],
    'dashboard')

client_auth_patterns = ([
    path(r'auth/',
         TemplateView.as_view(template_name='react_index.html'),
         name='auth_root'),
    path(r'auth/login',
         TemplateView.as_view(template_name='react_index.html'),
         name='login'),
    path(r'auth/recover-password',
         TemplateView.as_view(template_name='react_index.html'),
         name='recover_password'),
], 'auth')

urlpatterns = [
    path('accounts/', include('allauth.urls')),

    # path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('users/', include('apps.users.urls', namespace='users')),

    # React frontend support
    path('', include(dashboard_patterns, namespace='dashboard')),
    path('', include(client_auth_patterns, namespace='auth')),

    # DRF API urls
    path('api/v1/', include(api_urlpatterns, namespace='api')),

    # DJ-Stripe
    #path("stripe/", include('djstripe.urls', namespace="djstripe")),

    # Analytics
    # url('analytics/',
    # TemplateView.as_view(template_name='plotly_dash_template.html'),
    # name='analytics'),
    path('cratedb/',
         TemplateView.as_view(template_name='plotly_dash_template.html'),
         name='dash'),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),

    # Uploader
    path("uploader/", include('apps.uploader.urls')),

    # Website
    path(r'', TemplateView.as_view(template_name='index.html'), name='home'),
    path('library/',
         RedirectView.as_view(url='https://voxsnap.com/audiohub/', permanent=True, query_string=True)),
    path('privacy/',
         TemplateView.as_view(template_name='privacy.html'),
         name='privacy'),
    path('terms/',
         TemplateView.as_view(template_name='terms.html'),
         name='terms'),
    path('audiohub/', LibraryPageView.as_view(), name='library'),
    path('audiohub/<slug:customer>', AudioHubView.as_view(), name='audiohub'),

    # Sales inquiry / pricing
    path('pricing/', QuestionaireView.as_view(), name='pricing'),
    path('pricing/packages/', PackagesView.as_view(), name='packages'),
    path('pricing/packages/<package>',
         PackagesView.as_view(),
         name='packages_detail'),
    path('thank-you/',
         TemplateView.as_view(template_name='thank_you.html'),
         name='thank_you'),
    path('order-failed/', TemplateView.as_view(template_name='sales_custom/order-failed.html'), name='order-failed'),

    # Custom orders
    path('payment/atrium/', TemplateView.as_view(template_name='sales_custom/atrium.html')),
    path('payment/order/atrium/', AtriumPayment.as_view()),

    # Tim Draper book
    path('tim-draper/',
         TimDraperPlaylistView.as_view(),
         name='tim_draper_playlist'),

    # Blog posts
    path(
        'blog/why-converting-your-posts-to-audio-will-increase-your-'
        'marketing-roi/',
        TemplateView.as_view(
            template_name='blog/converting-posts-to-audio.html')),
    path(
        'blog/how-audio-demand-and-consumption-are-trending-up-and-why-you-'
        'should-be-part-of-it/',
        TemplateView.as_view(
            template_name='blog/audio-demand-trending-up.html')),
    path(
        'blog/how-content-marketing-can-help-you-boost-important-metrics-at-'
        'your-company/',
        TemplateView.as_view(template_name='blog/content-marketing.html')),
    path(
        'blog/voxsnap-launching-our-new-platform-to-transform-text-to-human-'
        'voice/',
        TemplateView.as_view(template_name='blog/new-platform.html')),
    #path('blog/', include('apps.blog.urls')),

    # Old hack for LinkedIn
    path(
        'img/facebook.png',
        RedirectView.as_view(
            url='https://cdn.voxsnap.com/v2/assets/img/facebook.png')),
]

if settings.PRODUCTION:
     urlpatterns += path('nimda/', admin.site.urls),
else:
     urlpatterns += path('admin/', admin.site.urls),

if settings.DEBUG:
    urlpatterns += re_path(r'^api/v1/api-auth/',
                           include('rest_framework.urls')),

    # This is only needed when using runserver.
    urlpatterns = \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
        + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
        + urlpatterns

    # # urls for testing error pages locally
    # from django.views.defaults import page_not_found, server_error
    #
    # errors_testing_patterns = [
    #     # url(r'^400/$', TemplateView.as_view(template_name='400.html')),
    #     # url(r'^403/$', TemplateView.as_view(template_name='403.html')),

apps/blog/models.py
from django.db import models
from django.core.validators import validate_integer

 # Create your models here.
class Blog(models.Model):
    STATUS = (
        ('D', 'Draft'),
        ('P', 'Published'))

    id = models.BigAutoField(primary_key=True)
    publish_date = models.DateField(auto_now_add=True)
    status = models.CharField(max_length=1, choices=STATUS, default='D', db_index=True)
    slug = models.SlugField(max_length=255, db_index=True)

    title = models.CharField(max_length=128)
    image = models.ImageField()
    description = models.TextField()

    player_username = models.CharField(max_length=64, blank=True, null=True)
    player_narration = models.CharField(max_length=30, blank=True, null=True, validators=[validate_integer])

    content = models.TextField(blank=True)

    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'Blog [{self.pk}], ({self.title}), status ({self.get_status_display()})'

apps/blog/views.py
from django.shortcuts import render
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import Blog

# Create your views here.

class BlogList(ListView):
    model = Blog
    template_name = 'blog_list.html'

class BlogPage(DetailView):
    model = Blog
    template_name = 'blog_page.html'

voxsnap/templates/audiohub.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Audiohub - {{ customer.company_name }}</title>
    <link rel="stylesheet" href="{% static "assets/css/style.min.css" %}">
    <meta property="fb:app_id" content="620074461518868" />
    <meta property="og:image" content="{% static "assets/img/logo_play_square.png" %}" />
    <meta name="twitter:image" content="{% static "assets/img/logo_play_square.png" %}" />
    <script>
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '335969666975527');
    fbq('track', 'PageView');
    </script>
  </head>
  <body>
    <header class="library-header">
      <div class="library-header__wrapper">
        <a href="/audiohub/" class="library-header__logo-link library-header__logo-link--audiohub" title="VoxSnap Audiohub">
          <img src="{% static "assets/img/logo-gray@2x.png" %}" width="136" height="18" alt="" class="audiohub-vx-img">
          <img src="{% static "assets/img/logo-audiohub.png" %}" width="151" height="18" alt="" class="audiohub-hub-img">
        </a>
      </div>
    </header>

    <section class="library-hub">
      <div class="library-hub__wrapper">
        <div class="library-hub__title">
          <!-- <img src="/assets/img/library/buffer.png" width="145" height="29px" alt="buffer" /> -->
        </div>
        <p class="library-hub__info">
          {{ customer.audio_hub_description }}
        </p>
        <div class="library-hub__link">
          <a href="{{ customer.website }}">{{ customer.website_display }}</a>
        </div>
      </div>
    </section>

    <section class="ask-va ask-va--bg-white">
  <div class="ask-va__wrapper">
    <div class="ask-va__inner">
      {% if customer.amazon_alexa %}
      <section class="ask-va__item">
        <div class="ask-va__title"><span>Ask your</span> Voice Assistant</div>
        <div class="ask-va__content">
          <div class="ask-va__logo">
            <img src="{% static "assets/img/library/va-alexa-rounded.png" %}" width="46" height="46" alt="Alexa" />
          </div>
          <p class="ask-va__text">
            <span>Alexa,</span> tell VoxSnap to play posts from {{ customer.company_name }}
          </p>
        </div>
      </section>
      {% endif %}

      {% if customer.podcasts %}
      <section class="ask-va__item">
        <div class="ask-va__title"><span>Find in your</span> Podcast App</div>
        <div class="ask-va__content ask-va__podcast">
          <div class="ask-va__logo">
            <img src="{% static "assets/img/library/apple-podcasts.jpg" %}" width="46" height="45" alt="Siri" />
          </div>
          <p class="ask-va__podcast-text">Listen in <span>Podcasts</span></p>
        </div>
      </section>
      {% endif %}
    </div>
  </div>
</section>


    <section class="library-list library-list--featured">
      <div class="library-list__wrapper">
        <div class="library-list__inner js-library-list-container">

        </div>
      </div>
    </section>

    <section class="lbr-player hidden-with-voxsnap" style="display: none;">
      <div id="voxsnap-player"></div>
    </section>

    <footer class="main-footer">
  <div class="main-footer__wrapper">
    <div class="main-footer__social">
      <a href="https://www.facebook.com/playaudiohub/" target="_blank" class="main-footer__social-link">
        <img src="{% static "assets/img/icon_fb.png" %}" width="20" height="20" alt="FaceBook">
      </a>
      <a href="https://twitter.com/playAudiohub/" target="_blank" class="main-footer__social-link">
        <img src="{% static "assets/img/icon_tw.png" %}" width="25" height="20" alt="Twitter">
      </a>
      <a href="https://www.instagram.com/playaudiohub/" target="_blank" class="main-footer__social-link">
        <img src="{% static "assets/img/icon_ins.png" %}" width="22" height="21" alt="Instagram">
      </a>
    </div>
    <div class="main-footer__info">
      <p class="made">
        <span>Made in </span>
        <span><img src="{% static "assets/img/us-flag.png" %}" width="20" height="15" alt="USA"></span>
      </p>
      <p class="legal">
        <a href="{% url 'terms' %}">Terms of Use</a>
        <a href="{% url 'privacy' %}">Privacy Policy</a>
      </p>
      <p class="copyright">
        Copyright &copy; {% now 'Y' %} VoxSnap Inc. All rights reserved.
      </p>
    </div>
  </div>
</footer>
    {% if PRODUCTION %}
    <script src="https://data.voxsnap.com/player/v1/voxsnap/voxsnap.js" data-audiohub="{{ customer.short_name }}" async></script>
    {% else %}
    <script src="http://localhost:1337/voxsnap_player_oop.js" type="module" data-audiohub="{{ customer.short_name }}" async></script>
    {% endif %}
    <!-- <script src="/assets/js/script.js"></script> -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-93567103-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-93567103-1');
    </script>
    <noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=335969666975527&ev=PageView&noscript=1" /></noscript>
  </body>
</html>

voxsnap/templates/base.html
{% load static compress %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block head_title %}{% endblock %} | {{ PROJECT_NAME }}</title>

    {% compress css %}
      {# <link rel="stylesheet" type="text/x-scss" href="{% static 'css/custom-style.scss' %}"/> #}
    {% endcompress %}
    <link rel="stylesheet" href="{% static "assets/css/style.min.css" %}">

    {% block styles %}{% endblock %}

    {{ HEAD_CLOSING|safe }}
  </head>
  <body>
    {% csrf_token %}

    {% block content %}{% endblock %}

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-93567103-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-93567103-1');
    </script>
    {% include "parts/scripts.html" %}

    {% block scripts %}{% endblock %}

    {{ BODY_CLOSING|safe }}
  </body>
</html>

voxsnap/templates/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta property="og:description" content="{% block meta_description %}{% endblock %}">
  <meta property="fb:app_id" content="620074461518868"/>
  <meta property="og:url" content="{% block meta_url %}{% endblock %}"/>
  <meta property="og:title" content="{% block meta_title %}{% endblock %}"/>
  <meta property="og:image" content="{% block meta_image %}{% endblock %}"/>
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@VoxSnap"/>
  <!-- <meta name="twitter:title" content="{{ meta_title }}"> -->
  <!-- <meta name="twitter:description" content="{{ meta_description }}"> -->
  <!-- <meta name="twitter:image" content="{{ meta_image }}"> -->
  <title>{% block head_title %}{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static "assets/css/style.min.css" %}">
</head>
<body>
  <header class="main-header">
  <div class="main-header__wrapper">
    <div class="main-header__inner">
      <div class="main-header__logo">
        <a href="/">
          <img src="{% static "assets/img/logo@2x.png" %}" width="168" height="23" alt="VoxSnap">
        </a>
      </div>
      <nav class="main-nav">
        <ul class="main-nav__list">
          <!-- <li><a href="/contact_us" class="main-nav__link">Contact</a></li> -->
          <li><a href="/pricing/" class="main-nav__link">Pricing</a></li>
          <li><a href="/audiohub/" class="main-nav__link">Audiohub</a></li>
          <li><a href="/#blog" class="main-nav__link main-nav__link--bold">Blog</a></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

  <main>
    <section class="blog-post">
      <div class="blog-post__wrapper">
        <section class="blog-post__cover">
          <img src="{% block blog_image %}{% endblock %}" alt />
        </section>
        <section class="blog-post__heading">
          <div class="blog-post__date">{{ blog_date }}</div>
          <h2 class="blog-post__title">{% block blog_title %}{% endblock %}</h2>
        </section>
        <section class="blog-post__content">
          {% block content %}{% endblock %}
        </section>
        <section class="blog-post__cta">
          <div class="blog-post__cta-title">GET STARTED BY ORDERING YOUR BLOG NARRATION</div>
          <a href="/pricing" class="blog-post__cta-btn">Start</a>
        </section>
      </div>
    </section>
  </main>

  <footer class="main-footer">
  <div class="main-footer__wrapper">
    <div class="main-footer__social">
      <a href="https://www.facebook.com/VoxSnap/" target="_blank" class="main-footer__social-link">
        <img src="{% static "assets/img/icon_fb.png" %}" width="20" height="20" alt="FaceBook">
      </a>
      <a href="https://twitter.com/VoxSnap/" target="_blank" class="main-footer__social-link">
        <img src="{% static "assets/img/icon_tw.png" %}" width="25" height="20" alt="Twitter">
      </a>
      <a href="https://www.instagram.com/voxsnap/" target="_blank" class="main-footer__social-link">
        <img src="{% static "assets/img/icon_ins.png" %}" width="22" height="21" alt="Instagram">
      </a>
    </div>
    <div class="main-footer__info">
      <p class="made">
        <span>Made in </span>
        <span><img src="{% static "assets/img/us-flag.png" %}" width="20" height="15" alt="USA"></span>
      </p>
      <p class="legal">
        <a href="/terms/">Terms of Use</a>
        <a href="/privacy/">Privacy Policy</a>
      </p>
      <p class="copyright">
        Copyright &copy; {% now 'Y' %} VoxSnap Inc. All rights reserved.
      </p>
    </div>
  </div>
</footer>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-93567103-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-93567103-1');
</script>
<script src="{% static "js/script.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

voxsnap/templates/email_base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block title %}VoxSnap Team{% endblock %} </title>

    {{ HEAD_CLOSING|safe }}
</head>
<body>

<div style="padding: 30px 20px 115px 20px;
            font-family: 'Open Sans', sans-serif;
            background-color: #d9e1ea"
            align="center">
    <div style="padding-bottom: 25px">
        <img src="https://voxsnap.com/img/logo@2x.png"
             width="336"
             height="46"
             alt="VoxSnap">
    </div>

    <div style="max-width: 600px;
                padding: 50px 20px 50px 20px;
                background-color: #fff"
         align="center">
        {% block content %}{% endblock %}
    </div>

    <div style="max-width: 640px;
                height: 45px;
                text-align: center;
                background-color: #cfd9e5">
        <span style="line-height: 45px;
                     font-size: 14px;
                     color: #586778">
            {% trans "E-mail from:" %} <a href="https://voxsnap.com/" style="text-decoration: none; color: #2c9ff9">VoxSnap</a>
        </span>
    </div>
</div>

{{ BODY_CLOSING|safe }}
</body>
</html>

voxsnap/templates/narration_detail.html
{% extends 'react_index.html' %}

{% block scripts %}
{{ block.super }}

{% endblock %}

voxsnap/templates/old_dashboard.html
{% extends 'base.html' %}

{% block head_title %}Index page{% endblock %}

{% block content %}
    <div>
        <h1>Index Page</h1>
        <a href="{% url 'dashboard:order_narrations' %}">Order</a>
        {% if user.is_authenticated %}
            <a href="{% url 'dashboard:narrations_list' %}">Narrations</a>
            <a href="{% url 'account_logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'auth:login' %}">Login</a>
        {% endif %}
    </div>
{% endblock %}

voxsnap/templates/plotly_dash_template.html
{% load static compress %}
{% load render_bundle from webpack_loader %}
{% load plotly_dash %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Voxsnap</title>

        {% plotly_header %}
        
        {% block app_header_css %}
        
        {% compress css %}
        <link rel="stylesheet" type="text/x-scss" href="{% static 'scss/app/analytics.scss' %}"></link>
        {% endcompress %}
        {% endblock%}
    </head>

    <body>
        <div id="root">
            <div class="dashboard-base">
                <div class="main-menu">
                    <div class="container">
                        <div class="nav-menu">
                            <a href="/" class="logo">
                                <img src="https://cdn.voxsnap.com/static/react/imgs/logo.svg" alt="Voxsnap">
                            </a>
                            <ul>
                                <li><a href="/narrations">Narrations</a></li>
                                <li><a href="/playlists">Playlists</a></li>
                                <li><a href="/distribution">Distribution</a></li>
                                <li><a class="active" aria-current="page" href="/analytics">Analytics</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="dashboard-content">
                    {% plotly_direct name="voxsnap" %}
                </div>
                <div class="footer">
                    <div class="nav-menu">
                        <ul>
                            <li><a href="/">Home</a></li>
                            <li><a href="/privacy">Privacy Policy</a></li>
                            <li><a href="/terms">Terms of Use</a></li>
                        </ul>
                    </div>
                    <div class="copyright text-right">
                        Copyright © 2019 VoxSnap Inc. All rights reserved.
                    </div>
                </div>
            </div>
        </div>
        {% plotly_footer %}
    </body>
</html>

voxsnap/templates/react_index.html
{% extends 'react_base.html' %}

{% block head_title %}Order{% endblock %}

{% block content %}
    <div id="root"></div>
{% endblock %}

{% block js_constants %}
    <script>
        window.STRIPE_API_KEY = '{{ STRIPE_PUBLIC_KEY }}';
    </script>
{% endblock %}